name: Tag merged PRs containing generated code with the version of the code

on:
  push:
    branches:
      master

jobs:
  tag:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Get last commit message
        id: commit_msg
        run: |
          {
            echo "msg<<EOF"
            git log -1 --pretty=%B
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Check if commit was from torngen/auto
        id: check_merge
        run: |
          echo "${{ steps.commit_msg.outputs.msg }}"
          if echo "${{ steps.commit_msg.outputs.msg }}" | grep -q 'torngen/auto'; then
            echo "continue=true" >> $GITHUB_OUTPUT
          else
            echo "continue=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit if not from torngen/auto
        if: steps.check_merge.outputs.continue != 'true'
        run: |
          echo "Merge not from torngen/auto, skipping tag."
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read version from torngen/VERSION
        id: read_version
        run: |
          echo "version=$(cat torngen/VERSION)" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.email "webmaster@deek.sh"
          git config user.name "dssecret"

          git tag "v${{ steps.read_version.outputs.version }}"
          git push origin "v${{ steps.read_version.outputs.version }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
